import sys

from google.adk import Agent
from opentelemetry import trace
from opentelemetry.trace import StatusCode

agent = Agent(
    name="Research_Agent", model="gemini-2.5-flash", instruction="Be a short factual assistant."
)

if __name__ == "__main__":
    print("--- Activating Agent Execution Loop ---")

    # Fetch the active span being generated by 'opentelemetry-instrument'
    current_span = trace.get_current_span()

    try:
        # Intentionally run the agent task
        response = agent.run("Give me a 1-sentence description of OpenTelemetry.")  # type: ignore[misc, call-arg, arg-type]

        # SUCCESS PATH: If it reaches here without raising an error, set status to OK
        print(f"[Research Agent Output]: {response.text}")  # type: ignore[attr-defined]
        current_span.set_status(StatusCode.OK, "Agent executed successfully.")

    except Exception as e:
        # FAILURE PATH: Catch any errors (API failures, bad credentials, rate limits)
        print(f"[ERROR] Agent failed execution: {e}", file=sys.stderr)

        # Explicitly tell Dynatrace this trace failed and log the exception payload
        current_span.set_status(StatusCode.ERROR, description=str(e))
        current_span.record_exception(e)

        # Re-raise the exception if you want the bash process to exit with a failure code
        raise e
